### ISSUE TITLE
Составить интро

### ISSUE THREAD

**Issue by AlexanderKhapchenko** [AlexanderKhapchenko/Geralt-From-Rivia-Porfolio#4]
Составить интро (вступление), где в 2-4 предложениях описать, что заказчик делает, что нравится делать, что хочется делать лучше, что важно делать, и т.д.

**Comment by AlexanderFox777** [comment]
<h2>Résumé</h2>
<p>&mdash; Я, Геральт из Ривии, прозванный эльфами и дриадами «Гвинблейдд», ведьмак школы Волка, первый клинок Севера. Живая легенда. 
&mdash; Прошел Испытание Травами, это крайне опасный процесс, из десяти подвергнутых ему в среднем выживает четверо или трое. Также преодолел мутацию глаз.
&mdash; Имею невероятно огромное количество закрытых контрактов, из которых, самые известные это: снятие проклятие, наложенное на принцессу Адду из Темерии; изгнание джинна из Ринды; победа в схватке с Гюнтер о’Димом, который по многим легендам являлся демоном; убийство короля Дикой Охоты; избавление Туссента по княжеской просьбе от опасного чудовища.
</p>

**Comment by AlexanderKhapchenko** [comment]
Благодарю
