### ISSUE TITLE
Составить таймлайн

### ISSUE THREAD

**Issue by AlexanderKhapchenko** [AlexanderKhapchenko/Geralt-From-Rivia-Porfolio#6]
Составить список всех (важных) жизненных событий, памятных дат, достижений, периодов, которые дали приятный и неприятный опыт, и т.п. В этом конкретном случае длинных списков не бывает, бывают плохо свернутые, поэтому пакуем сюда всё подряд, а про "лишние" события можно будет промолчать позже. Список должен быть систематизирован и отсортирован таким образом, чтоб читатель быстро понял "паттерн" и мог легко ориентироваться в пространстве и времени этого резюме.

**Comment by AlexanderFox777** [comment]
<section>
                        <h3>Опыт</h3>
                        <h6>Сейчас</h6>
                        <ul class="timeline">
                            <li class="highlighted">
                                <p><em>1<sup>го</sup> Января 2020 – сейчас</em></p>
                                <p><strong>Избавления от проклятия</strong> <strong><a href="https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D1%80%D0%BE%D0%BD%D0%B0%D0%B2%D0%B8%D1%80%D1%83%D1%81%D1%8B" rel="external">короновируса</a></strong></p>
                                <ul>
                                    <li class="details">
                                        <input type="checkbox" id="other">
                                        <label for="other" class="summary">поиск источника</label>
                                        <div>
                                            <ul>
                                                <li>поиск первого пациента в Ухани</li>
                                                <li>убеждение о закрытии границы в Китае</li>
                                                <li>разговор с королем вампиров о летучих мышах</li>
                                                <li>опревережение слухов о скрытой лаборатории</li>
                                                <li>нахождение информации о первом пациенте не с Китая</li>
                                                <li>обнаружение первого пациента</li>
                                            </ul>
                                        </div>
                                    </li>
                                    <li class="details">
                                        <input type="checkbox" id="other">
                                        <label for="other" class="summary">разработка мутагенов для ведьмаков от короновируса</label>
                                        <div>
                                            <ul>
                                                <li>тестирование зеленых мутагенов для увеличения здоровья, чтобы добиться более длительного времени на лечение</li>
                                                <li>тестирование синих мутагенов для увеличение маны, чтобы добиться более сложных заклятий исцеления</li>
                                                <li>тестирование красных мутагенов для увеличение атаки, чтобы добиться атаки организма на вирус</li>
                                                <li>хаотичное смешивание разных мутагенов с помощью Йенифер и получения вакцины для ведьмаков</li>
                                                <li>расширение штаба ведьмаков для ускорения поисков новых ингридиентов</li>                                  
                                            </ul>
                                        </div>
                                    </li>
                                    <li>тестирование вакцины на людях не подверженных мутациям</li>
                                    <li>поиск вора рабочей вакцины</li>
                                </ul>
                            </li>
                        </ul>
                        <h6>Раньше</h6>
                        <ul class="timeline">
                            <li>
                                <p><em>5<sup>го</sup> Апреля 2019 – 31<sup>го</sup> Декабря 2019</em></em></p>
                                <p><strong>Продвижение меня</strong></p>
                                <ul>
                                    <li class="details">
                                        <input type="checkbox" id="other">
                                        <label for="other" class="summary">Подробнее</label>
                                        <div style="margin-bottom: 0.25em;">
                                            <small><em>(Не совсем понимаю что они обо мне пишут, но это работает)</em></small>
                                        </div>
                                        <div>
                                            <ul>
                                                <li>Продвижение в соц сетях</li>
                                                <li>Разработка портфолио</li>
                                                <li>Работа над имиджом</li>
                                                <li>Поиск монстров</li>
                                                <li>Нахождение фан клубов</li>
                                                <li>Спонсирование тик ток для взаимовыгодной рекламы</li>
                                                <li>Закупка рекламы у блогеров</li>
                                                <li>Нанимание постоянного штаба людей которые следят за моей популярностью</li>
                                            </ul>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <p><em>1<sup>го</sup> Января 2019 – 2<sup>го</sup> Апреля 2019</em></em></p>
                                <p><strong>Работа продавцом-консультантом</strong> в <strong><a href="https://www.citrus.ua/" rel="external">Citrus</a></strong></p>
                                <ul>
                                    <li class="details">
                                        <input type="checkbox" id="other">
                                        <label for="other" class="summary">Награды</label>
                                        <div style="margin-bottom: 0.25em;">
                                            <small><em>(С помощью знака Аксий, который внушает, продавать не так уже и сложно)</em></small>
                                        </div>
                                        <div>
                                            <ul>
                                                <li>Лучший продавец недели</li>
                                                <li>Лучший продавец месяца</li>
                                                <li>Лучший продавец мира</li>
                                                <li>Повышения до главного продавца</li>
                                                <li>Повышения до зам администратора</li>
                                                <li>Повышения до зам администратора</li>
                                                <li>Перевод работы в пассивный доход</li>
                                                <li>Поиск работы, которая больше по душе</li>
                                            </ul>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <p><em>7<sup>го</sup> Июня 1280 – 31<sup>го</sup> Декабря 2018</em></em></p>
                                <p><strong>Телепортация во времени</strong> благодаря <strong><a href="https://vedmak.fandom.com/wiki/%D0%99%D0%B5%D0%BD%D0%BD%D0%B8%D1%84%D1%8D%D1%80" rel="external">Йенифер</a></strong></p>
                                <ul>
                                    <li class="details">
                                        <input type="checkbox" id="other">
                                        <label for="other" class="summary">Тестирования новых заклинаний телепортации почему-то на мне</label>
                                        <div>
                                            <ul>
                                                <li>первые 37 раз ощущался запах жареной курицы, опытный маг Йенифер уверяла что так и должно быть</li>
                                                <li>телепортация во времени на час вперед</li>
                                                <li>попутное исправления формулы Йенифер</li>
                                                <li>телепортация меня в 2018ый год</li>
                                            </ul>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                        <h6>Еще раньше</h6>
                        <div style="margin-bottom: 0.25em;">
                            <small><em>(Многое произошло, описано самое знаменитое и то что вспомнил Геральт)</em></small>
                        </div>
                        <ul class="timeline">
                            <li>
                                <p><em>1275</em></p>
                                <ul>
                                    <li class="details">
                                        <input type="checkbox" id="other">
                                        <label for="other" class="summary">Чудовище в Туссенте</label>
                                        <div>
                                            <ul>
                                                <li>Поиск улик около жертв</li>
                                                <li>Нахождения монстра, который оказываеться высшим вампиром</li>
                                                <li>Осознания сложности ситуации ибо вампиром манипулируют</li>
                                                <li>Получение во владение Corvo Bianco</li>
                                                <li>Дун Тинн атакует полк гвардии Туссена под командованием Дамьена де ла Тур и с помощью меня. Там Сильвия Анна схвачена после ее попытки манипулировать Детлаффом ван дер Эретейном, чудовищем Боклера, чтобы убить рыцарей, которые обидели ее</li>
                                                <li>Имлерит, Карантир Ар-Фейниэль и Эредин Бреак Глас убиты, а Дикая Охота побеждена.</li>
                                                <li>Пробитие осады вампиров под командованием Детлаффа</li>
                                                <li>Убийство Деталффа</li>
                                                <li>Примерение двух враждующий сестер</li>
                                            </ul>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <p><em>1272</em></p>
                                <ul>
                                    <li class="details">
                                        <input type="checkbox" id="other">
                                        <label for="other" class="summary">Уничтожение Дикой Охоты и другие события</label>
                                        <div>
                                            <ul>
                                                <li>Битва за Белый сад</li>
                                                <li>Поиски Йенифер</li>
                                                <li>Отбитие нескольких атак Дикой Охооты</li>
                                                <li>Создания плана по уничтожению Дикой Охоты</li>
                                                <li>Дикая Охота атакует Каэр Морхена, чтобы добраться до Цири, но в конечном итоге вынуждена отступить. Весемир убит в процессе</li>
                                                <li>Имлерит, Карантир Ар-Фейниэль и Эредин Бреак Глас убиты, а Дикая Охота побеждена.</li>
                                                <li>Помощь Цири в успешном добитии Белого Мороза</li>
                                            </ul>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <p><em>1271</em></p>
                                <ul>
                                    <li class="details">
                                        <input type="checkbox" id="other">
                                        <label for="other" class="summary">Войны и осады</label>
                                        <div>
                                            <ul>
                                                <li>Сопровождение темерского короля при осаде замка Ла-Валетт</li>
                                                <li>Помогощь в разрешении конфликта в долине Понтара и обнаружение, что таинственный убийца сотрудничал с Ложей Чародеек</li>
                                                <li>Участие в Третьей Северной войне</li>
                                            </ul>
                                        </div>
                                    </li>
                                </ul>
                            </li>                           
                            <li>
                                <p><em>23<sup>го</sup> Ноября 1269</em></p>
                                <p><strong>В деревне Колдуотер в Синтре преследую Дикую Охоту</strong></p>
                            </li>
                            <li>
                                <p><em>13<sup>го</sup> Сентября 1269</em></p>
                                <p><strong>В ущелье Гидры преследую Дикую Охоту</strong></p>
                            </li>
                            <li>
                                <p><em>1269</em></p>
                                <p><strong>Дикая Охота выслеживает меня и Йеннифэр, похищая колдунью, чтобы вытащить Цири из укрытия. Я следует за ними, пересекая границы между мирами исключительно силой воли.</strong></p>
                            </li>
                            <li>
                                <p><em>1218</em></p>
                                <p><strong>Битва при Лисьей лощине</strong></p>
                            </li>              
                        </ul>
                    </section>

**Comment by AlexanderKhapchenko** [comment]
Спасибо
