### ISSUE TITLE
Составить дополнительные информационные блоки

### ISSUE THREAD

**Issue by AlexanderKhapchenko** [AlexanderKhapchenko/Geralt-From-Rivia-Porfolio#7]
Можно сделать резюме менее формальным, добавив дополнительные блоки, которые содержат полезную информацию, но подают её в "развлекательной" форме. Например, что нравится и не нравится, сильные и слабые стороны, перечень навыков или хобби, инфографика или же интерактивные модули, и т.п. Стоит написать контент такого блока раньше, чем начинать верстку, потому что его размеры будут влиять на размещение элементов на странице.

**Comment by AlexanderFox777** [comment]
<section>
                    <h3>Языки</h3>
                    <p class="tags small"><a href="/uk-ua" hreflang="uk" rel="alternate" class="language" lang="uk">&#x1f1fa;&#x1f1e6; <span>УКРАЇНСЬКА</span></a> <a href="/ru-ru" hreflang="ru" rel="alternate" class="language" lang="ru">&#x1f1f7;&#x1f1fa; <span>РУССКИЙ</span></a> <span class="language" lang="en">&#x1f1fa;&#x1f1f8; ENGLISH</span></p>
                </section>

**Comment by AlexanderFox777** [comment]
<h3>Языки</h3>
                    <p class="tags small"><a href="/uk-ua" hreflang="uk" rel="alternate" class="language" lang="uk">&#x1f1fa;&#x1f1e6; <span>УКРАЇНСЬКА</span></a> <a href="/ru-ru" hreflang="ru" rel="alternate" class="language" lang="ru">&#x1f1f7;&#x1f1fa; <span>РУССКИЙ</span></a> <span class="language" lang="en">&#x1f1fa;&#x1f1f8; ENGLISH</span></p>

**Comment by AlexanderFox777** [comment]
<h3>Навыки</h3>
                    <p class="tags small"><span class="nowrap">СОЗДАНИЕ МУТАГЕНОВ </span> <span class="nowrap">СНЯТИЕ ПРОКЛЯТИЙ</span> ФЕХТОВАНИЕ <span class="nowrap">ОТРАЖЕНИЕ СТРЕЛ</span> <span class="nowrap">МАГИЧЕСКИЕ ЗНАКИ</span> <span class="nowrap"> АЛХИМИЯ </span> <span class="nowrap">ХОДЯЧИЙ БЕСТИАРИЙ</span> <span class="nowrap">ТЕХНИКА ШКОЛЫ КОТА</span> <span class="nowrap">ИНСТИНКТ ВЫЖИВАНИЯ</span> <span class="nowrap">ВЫБРОС АДРЕНАЛИНА</span> <span class="nowrap">УПРАВЛЕНИЕ ГНЕВОМ</span> <span class="nowrap">ВЗРЫВНОЙ ЩИТ</span> <span class="nowrap">ОГНЕННЫЙ ПОТОК</span> <span class="nowrap">БЫСТРЫЙ МЕТАБОЛИЗМ</span> <span class="nowrap">МАГИЧЕСКАЯ ЛОВУШКА</span></p>

**Comment by AlexanderFox777** [comment]
<h3>Характер</h3>
                    <p class="tags small"><a href="https://www.reddit.com/r/4chan/" rel="external">СПЕЦИФИЧНОЕ ЧУВСТВО ЮМОРА</a> СДЕРЖАННОСТЬ МОЛЧАЛИВОСТЬ ПРЯМОЛИНЕЙНОСТЬ ЧЕСТНОСТЬ КРАСНОРЕЧИЕ ЛЮБОЗНАТЕЛЬНОСТЬ РАССУДИТЕЛЬНОСТЬ СКРЫТНОСТЬ ПРАКТИЧНОСТЬ НЕПРИХОТЛИВОСТЬ НЕЗАВИСИМОСТЬ СООБРАЗИТЕЛЬНОСТЬ РАЗУМНОСТЬ МУДРОСТЬ САРКАСТИЧЕН</p>

**Comment by AlexanderFox777** [comment]
<h3>Характер</h3>
                    <p class="tags small"><a href="https://www.reddit.com/r/4chan/" rel="external">СПЕЦИФИЧНОЕ ЧУВСТВО ЮМОРА</a> СДЕРЖАННОСТЬ МОЛЧАЛИВОСТЬ ПРЯМОЛИНЕЙНОСТЬ ЧЕСТНОСТЬ КРАСНОРЕЧИЕ ЛЮБОЗНАТЕЛЬНОСТЬ РАССУДИТЕЛЬНОСТЬ СКРЫТНОСТЬ ПРАКТИЧНОСТЬ НЕПРИХОТЛИВОСТЬ НЕЗАВИСИМОСТЬ СООБРАЗИТЕЛЬНОСТЬ РАЗУМНОСТЬ МУДРОСТЬ САРКАСТИЧЕН</p>

**Comment by AlexanderFox777** [comment]
<h3>Нравится&#x1f603;</h3>
                    <p class="tags small"> <span class="nowrap">НАТОЧЕННЫЕ МЕЧИ</span> <span class="nowrap">УДАЧНЫЕ МУТАГЕНЫ</span> <span class="nowrap">СКИДКИ НА МЕЧИ И БРОНЮ</span> ​ЙЕНИФЕР <button id="midnightblue" class="color midnightblue">ПОЛУНОЧНЫЙ СИНИЙ</button> НОЧЬ ЧЕСТНОСТЬ ПЛОТВА </p>

**Comment by AlexanderFox777** [comment]
<h3>Не нравится&#x1f61e;</h3>
                    <p class="tags small">ВРАНЬЕ <button id="red" class="color red">КРАСНЫЙ</button> ПОЛИТИКА <span class="nowrap">БЕСПЛАТНЫЕ ЗАКАЗЫ</span> <span class="nowrap">ЗАТУПЛЕННОЕ ОРУЖИЕ</span> ТЕЛЕПОРТАЦИЯ</p>

**Comment by AlexanderFox777** [comment]
<h3>Хочется&#x1f97a;</h3>
                    <p class="tags small bulleted"><span class="tag">ЗДОРОВЬЯ БЛИЗКИМ</span><span class="tag">БОЛЬШИХ ПОБЕД В ГВИНТ</span><span class="tag">ОТДЫХ С ЙЕНИФЕР</span><span class="tag">СОЗДАТЬ ЛИЧНЫЙ БРЕНД</span><span class="tag">ЗАВЕСТИ С ЙЕНИФЕР ДЕТЕЙ</span><span class="tag">ИНТЕРЕСНЫХ ЗАКАЗОВ</span><span class="tag">ЧТОБЫ ПЛОТВА НЕ ТУПИЛА</span></p>

**Comment by AlexanderFox777** [comment]
<h3>Образование</h3>
<ul class="timeline">
                      <li>
                        <div><em>Очень давно</em></div>
                        <div><strong>Становление ведьмаком</strong> в одной из шести известных ведьмачих школ <strong>Каэр Морхен</strong></div>
                      </li>
                    </ul>

**Comment by AlexanderFox777** [comment]
<h3>Книги про меня</h3>
                    <p class="tags small bulleted"><span class="tag">ПОСЛЕДНЕЕ ЖЕЛАНИЕ</span><span class="tag">МЕЧ ПРЕДНАЗНАЧЕНИЯ</span><span class="tag">КРОВЬ ЭЛЬФОВ</span><span class="tag">ЧАС ПРЕЗРЕНИЯ</span><span class="tag">КРЕЩЕНИЕ ОГНЕМ</span><span class="tag">БАШНЯ ЛАСТОЧКИ</span><span class="tag">ВЛАДЫЧИЦА ОЗЕРА</span><span class="tag">СЕЗОН ГРОЗ</span></p>

**Comment by AlexanderFox777** [comment]
<h3>Articles</h3>
                    <p>None published <sup><em>yet</em></sup></p>

**Comment by AlexanderKhapchenko** [comment]
Огромное спасибо
